src/accounts/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.contrib import admin
from .views import (login_view, register_view, logout_view, change_password)

urlpatterns = [
    url(r'^login/$',login_view, name='login'),
    url(r'^register/$', register_view, name='register'),
    url(r'^password/change/$', change_password, name='change_password'),
    url(r'^logout/$', logout_view, name='logout')
]

src/respocare/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from product.views import home,ProductList,ProductCreate,ProductUpdate
from invoice.views import InvoiceList, create_invoice, update_invoice, invoice_view, invoice_pdf_view, pdf_view
from inventory.views import InventoryList,InventoryCreate,InventoryUpdate



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name='home'),
    url(r'^invoice/view/(?P<id>[\d]+)/$', invoice_view, name='invoice_view'),
    url(r'^invoice/pdf/view/(?P<id>[\d]+)/$', invoice_pdf_view, name='invoice_pdf_view'),
    url(r'^invoice/pdf/download/(?P<id>[\d]+)/$', pdf_view, name='pdf_view'),
    url(r'^product/list/$', ProductList.as_view(), name="product_list"),
    url(r'^product/create/$', ProductCreate.as_view(), name="product_create"),
    url(r'^product/update/(?P<pk>[\d]+)/$', ProductUpdate.as_view(), name="product_update"),
    url(r'^invoice/list/$', InvoiceList.as_view(), name="invoice_list"),
    url(r'^invoice/create/$', create_invoice, name="invoice_create"),
    url(r'^inventory/list/$', InventoryList.as_view(), name="inventory_list"),
    url(r'^inventory/create/$', InventoryCreate.as_view(), name="inventory_create"),
    url(r'^inventory/update/(?P<pk>[\d]+)/$', InventoryUpdate.as_view(), name="inventory_update"),
    url(r'^invoice/update/(?P<id>[\d]+)/$', update_invoice, name="update_invoice"),
    url(r'^accounts/', include("accounts.urls")),

]


admin.site.site_header = "RESPO CARE ADMIN"
admin.site.site_title = "RESPO CARE"

src/inventory/models.py
from django.db import models
from product.models import Product


# Create your models here.
class Inventory(models.Model):
	product 		= models.OneToOneField(Product)
	total_stock   	= models.PositiveIntegerField(default=100)
	stock   		= models.PositiveIntegerField(default=100)
	create_date     = models.DateTimeField(auto_now = True,auto_now_add = False)
	update 		    = models.DateTimeField(auto_now = False,auto_now_add = True)

	def __str__(self):
		return str(self.product)

src/inventory/forms.py
from django.forms import ModelForm, inlineformset_factory, TextInput
from .models import Inventory


class InventoryForm(ModelForm):
	class Meta:
		model = Inventory
		fields = '__all__'

src/inventory/views.py
from django.shortcuts import render
from django.views.generic import ListView,CreateView,UpdateView
from .models import Inventory
from .forms import InventoryForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


class InventoryList(LoginRequiredMixin, ListView):
	model = Inventory
	template_name = 'inventory/inventory_list.html'
	context_object_name = 'inventory_list'
	ordering = "-pk"

	def get_context_data(self,**kwargs):
		data = super(InventoryList,self).get_context_data(**kwargs)
		data["inventory_form"] = InventoryForm()
		return data

class InventoryCreate(LoginRequiredMixin, CreateView):
	model = Inventory
	template_name = 'inventory/inventory_create.html'
	form_class = InventoryForm
	success_url = '/inventory/list/'

class InventoryUpdate(LoginRequiredMixin, UpdateView):
	model = Inventory
	template_name = 'inventory/inventory_update.html'
	form_class = InventoryForm
	success_url = '/inventory/list/'

src/templates/inventory/inventory_list.html
{% extends 'base.html' %}
{% block contain %}

<style media="screen">
  #id_product{
    width: 55%;
  }
</style>

 <div class="container">
            <div class="inner-container">
                <button id="myBtn">Create Inventory</button>
                    <div id="myModal" class="modal">
                        <div class="modal-content"  style="width: 50%;">
                            <div class="modal-header">
                                <span class="close">&times;</span>
                                <h2>Create Inventory</h2>
                            </div>
                            <div class="modal-body" style="margin-bottom: 10%;">
                            <form action="{% url 'inventory_create' %}" method="POST" enctype="multipart/form-data"  style="margin-left: 8%;">{% csrf_token %}

                              {% for field in inventory_form.visible_fields %}
                              <br>
                              {{ field.label_tag }}<br>
                              {{ field }}
                              <br>
                              {% endfor %}
                              <button type="submit" style="float: left;margin-top: 12px">Submit</button>
                            </form>
                              </div>
                        </div>
                    </div>
                <div class="invoicelist">
                    <div class="table-header">
                        <h3>Inventory List</h3>
                        <hr>
                    </div>
                    <div class="table-list">
                        <table id="table">
                            <tr>
                                <th class="col col-1">#Id</th>
                                <th class="col col-2">Product Name</th>
                                <th class="col col-3">Stock</th>
                                <th class="col col-5">Create Date</th>
                                <th class="col col-6">Edit</th>
                            </tr>


    {% for product in inventory_list %}

                       <tr>
                              <td>#{{ product.id }}</td>
                              <td>{{ product.product.name }}</td>
                              <td>{{ product.stock}}</td>

                              <td>{{ product.create_date|date:"Y-m-d" }}</td>

                             <td><a href="{% url 'inventory_update' product.id %}"><i class="far fa-file-alt"></i></a></td>
                          </tr>
                        {% endfor %}



                        </table>
                    </div>
                </div>

              </div>
</div>

{% endblock %}

src/templates/inventory/inventory_update.html
{% extends 'base.html' %}
{% block contain %}

<div style="margin-top: 1%;margin-left: 17%;">
	<p>Update Inventory</p>
	<hr>
</div>

<div style="margin-left: 17%;margin-top: 2%;">
	<form action="" method="POST">{% csrf_token %}

{% for field in form.visible_fields %}
<br>
{{ field.label_tag }}<br>
{{ field }}
<br>
{% endfor %}
<br>
	<button style="float: left;" type="submit">Update</button>

</form>
</div>
<style media="screen">
  #id_product{
    width: 45%;
  }
</style>

{% endblock %}