src/accounts/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.contrib import admin
from .views import (login_view, register_view, logout_view, change_password)

urlpatterns = [
    url(r'^login/$',login_view, name='login'),
    url(r'^register/$', register_view, name='register'),
    url(r'^password/change/$', change_password, name='change_password'),
    url(r'^logout/$', logout_view, name='logout')
]

src/respocare/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from product.views import home,ProductList,ProductCreate,ProductUpdate
from invoice.views import InvoiceList, create_invoice, update_invoice, invoice_view, invoice_pdf_view, pdf_view
from inventory.views import InventoryList,InventoryCreate,InventoryUpdate



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name='home'),
    url(r'^invoice/view/(?P<id>[\d]+)/$', invoice_view, name='invoice_view'),
    url(r'^invoice/pdf/view/(?P<id>[\d]+)/$', invoice_pdf_view, name='invoice_pdf_view'),
    url(r'^invoice/pdf/download/(?P<id>[\d]+)/$', pdf_view, name='pdf_view'),
    url(r'^product/list/$', ProductList.as_view(), name="product_list"),
    url(r'^product/create/$', ProductCreate.as_view(), name="product_create"),
    url(r'^product/update/(?P<pk>[\d]+)/$', ProductUpdate.as_view(), name="product_update"),
    url(r'^invoice/list/$', InvoiceList.as_view(), name="invoice_list"),
    url(r'^invoice/create/$', create_invoice, name="invoice_create"),
    url(r'^inventory/list/$', InventoryList.as_view(), name="inventory_list"),
    url(r'^inventory/create/$', InventoryCreate.as_view(), name="inventory_create"),
    url(r'^inventory/update/(?P<pk>[\d]+)/$', InventoryUpdate.as_view(), name="inventory_update"),
    url(r'^invoice/update/(?P<id>[\d]+)/$', update_invoice, name="update_invoice"),
    url(r'^accounts/', include("accounts.urls")),

]


admin.site.site_header = "RESPO CARE ADMIN"
admin.site.site_title = "RESPO CARE"

src/product/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Product(models.Model):
	name 		   = models.CharField(max_length=100)
	description	   = models.TextField(max_length=100)
	vendor		   = models.CharField(max_length=100)  
	create_date    = models.DateTimeField(auto_now = True,auto_now_add = False)
	update 		   = models.DateTimeField(auto_now = False,auto_now_add = True)

	def __str__(self):
		return self.name

src/product/forms.py
from django.forms import ModelForm, inlineformset_factory, TextInput
from .models import Product


class ProductForm(ModelForm):
	class Meta:
		model = Product
		fields = '__all__'

src/product/views.py
from django.shortcuts import render
from django.views.generic import ListView,CreateView,UpdateView
from .models import Product
from invoice.models import Invoice
from .forms import ProductForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
# Create your views here.
@login_required
def home(request):
	invoice = Invoice.objects.all().order_by("-pk")
	todays_sell = 0
	todays_invs = invoice.filter(invoice_date = timezone.now().date())
	for inv in todays_invs:
		todays_sell = todays_sell + inv.total_invoice_price
	product = Product.objects.all()
	context = {
		"total_invoice":invoice.count(),
		"recent_invoice":invoice[:5],
		"total_product":product.count(),
		"todays_sell":todays_sell,
	}
	return render(request,'home.html', context)

class ProductList(LoginRequiredMixin, ListView):
	model = Product
	template_name = 'product/product_list.html'
	context_object_name = 'product_list'
	ordering = "-pk"

	def get_context_data(self,**kwargs):
		data = super(ProductList,self).get_context_data(**kwargs)
		data["product_form"] = ProductForm()
		return data

class ProductCreate(LoginRequiredMixin, CreateView):
	model = Product
	template_name = 'product/product_create.html'
	form_class = ProductForm
	success_url = '/product/list/'

class ProductUpdate(LoginRequiredMixin, UpdateView):
	model = Product
	template_name = 'product/product_update.html'
	form_class = ProductForm
	success_url = '/product/list/'

src/templates/product/product_list.html
{% extends 'base.html' %}
{% block contain %}

<div class="container">
<div class="inner-container">
        <button id="myBtn">Create Product</button>
            <div id="myModal" class="modal">
                <div class="modal-content" style="width: 50%;">
                    <div class="modal-header">
                        <span class="close">&times;</span>
                        <h2>Create Product</h2>
                    </div>
                    <div class="modal-body" style="margin-bottom: 10%;">
                      <form action="{% url 'product_create' %}" method="POST" enctype="multipart/form-data" style="margin-left: 8%;">{% csrf_token %}

                      {% for field in product_form.visible_fields %}
                      <br>
                      {{ field.label_tag }}<br>
                      {{ field }}
                      <br>
                      {% endfor %}
                      <button type="submit" style="float: left;margin-top: 12px">Submit</button>
                      </form>
                    </div>
                </div>
            </div>
                <div class="invoicelist">
                    <div class="table-header">
                        <h3>Product List</h3>
                        <hr>
                    </div>
                    <div class="table-list">
                        <table id="table">
                            <tr>
                                <th class="col col-1">#Id</th>
                                <th class="col col-2">Name</th>
                                <th class="col col-3">Description</th>
                                <th class="col col-4">Vendor</th>
                                <th class="col col-5">Create Date</th>
                                <th class="col col-6">Edit</th>
                            </tr>


                        {% for product in product_list %}

                       <tr>
                              <td>#{{ product.id }}</td>
                              <td>{{ product.name }}</td>
                              <td>{{ product.description|truncatechars:20 }}</td>
                              <td>{{ product.vendor }}</td>
                              <td>{{ product.create_date|date:"Y-m-d" }}</td>

                          <td><a href="{% url 'product_update' product.id %}"><i class="far fa-file-alt"></i></a></td>
                          </tr>
                        {% endfor %}



                        </table>
                    </div>
                </div>

              </div>
            </div>

{% endblock %}

src/templates/product/product_update.html
{% extends 'base.html' %}

{% block contain %}

<div style="margin-top: 1%;margin-left: 17%;">
	<p>Update Product</p>
	<hr>
</div>

<div style="margin-left: 17%;
margin-top: 2%;">
	<form action="" method="POST">{% csrf_token %}




{% for field in form.visible_fields %}
<br>
{{ field.label_tag }}<br>
{{ field }}
<br>
{% endfor %}
<br>
	<button style="float: left;" type="submit">Update</button>

</form>

</div>
<style>
	#id_name{
		width: 41% !important;
	}
	#id_description{
		width: 42% !important;
	}
	#id_vendor{
		width: 35% !important;
	}
</style>

{% endblock %}