src/accounts/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.contrib import admin
from .views import (login_view, register_view, logout_view, change_password)

urlpatterns = [
    url(r'^login/$',login_view, name='login'),
    url(r'^register/$', register_view, name='register'),
    url(r'^password/change/$', change_password, name='change_password'),
    url(r'^logout/$', logout_view, name='logout')
]

src/respocare/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from product.views import home,ProductList,ProductCreate,ProductUpdate
from invoice.views import InvoiceList, create_invoice, update_invoice, invoice_view, invoice_pdf_view, pdf_view
from inventory.views import InventoryList,InventoryCreate,InventoryUpdate



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name='home'),
    url(r'^invoice/view/(?P<id>[\d]+)/$', invoice_view, name='invoice_view'),
    url(r'^invoice/pdf/view/(?P<id>[\d]+)/$', invoice_pdf_view, name='invoice_pdf_view'),
    url(r'^invoice/pdf/download/(?P<id>[\d]+)/$', pdf_view, name='pdf_view'),
    url(r'^product/list/$', ProductList.as_view(), name="product_list"),
    url(r'^product/create/$', ProductCreate.as_view(), name="product_create"),
    url(r'^product/update/(?P<pk>[\d]+)/$', ProductUpdate.as_view(), name="product_update"),
    url(r'^invoice/list/$', InvoiceList.as_view(), name="invoice_list"),
    url(r'^invoice/create/$', create_invoice, name="invoice_create"),
    url(r'^inventory/list/$', InventoryList.as_view(), name="inventory_list"),
    url(r'^inventory/create/$', InventoryCreate.as_view(), name="inventory_create"),
    url(r'^inventory/update/(?P<pk>[\d]+)/$', InventoryUpdate.as_view(), name="inventory_update"),
    url(r'^invoice/update/(?P<id>[\d]+)/$', update_invoice, name="update_invoice"),
    url(r'^accounts/', include("accounts.urls")),

]


admin.site.site_header = "RESPO CARE ADMIN"
admin.site.site_title = "RESPO CARE"

src/invoice/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import Product
from inventory.models import Inventory
from django.db.models.signals import pre_save, post_save

class Invoice(models.Model):
	invoice_to 		= models.TextField()
	invoice_note 	= models.TextField(null=True, blank=True)
	invoice_date 	= models.DateTimeField()
	discount     	= models.PositiveIntegerField(default=0)
	total_invoice_price = models.PositiveIntegerField(default=0)
	created_by   	= models.ForeignKey(User,on_delete=models.CASCADE)


	def __str__(self):
		return self.invoice_to



class InvoiceProduct(models.Model):
	invoice = models.ForeignKey(Invoice,on_delete=models.CASCADE)
	total_price = models.PositiveIntegerField(default=0)
	price       = models.PositiveIntegerField(default=0)
	quantity	= models.PositiveIntegerField(default=1)
	product 	= models.ForeignKey(Product,on_delete=models.CASCADE)

	def __str__(self):
		return str(self.product)

src/invoice/forms.py
from django.forms import ModelForm, inlineformset_factory
from .models import InvoiceProduct, Invoice

class InvoiceForm(ModelForm):
    class Meta:
        model = Invoice
        exclude = ['created_by','total_invoice_price']


class InvoiceProductForm(ModelForm):
    class Meta:
        model = InvoiceProduct
        exclude = ['total_price']


invoice_inline_form = inlineformset_factory(Invoice, InvoiceProduct,form=InvoiceProductForm, extra=1)

src/invoice/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Invoice, InvoiceProduct
from django.views.generic import ListView
from .forms import invoice_inline_form, InvoiceForm, InvoiceProductForm
from django.db import transaction
from inventory.models import Inventory
from product.models import Product
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

import pdfkit


options = {
    'page-size': 'Letter',
    'margin-top': '0.5in',
    'margin-right': '0.5in',
    'margin-bottom': '0.5in',
    'margin-left': '0.5in',
    'encoding': "UTF-8",
    'no-outline': None
}




def invoice_pdf_view(request,id):
	invoice_obj = Invoice.objects.get(id=id)
	context = {
	'invoice_obj':invoice_obj
	}
	return render(request, "invoice/invoice_pdf_view.html",context)


def pdf_view(request,id=None):
	projectUrl = request.get_host() + '/invoice/pdf/view/' + id + '/'
	pdf = pdfkit.from_url(projectUrl, False, options=options)
	response = HttpResponse(pdf,content_type='application/pdf')
	response['Content-Disposition'] = 'inline; filename="invoice.pdf"'
	# attachment
	return response



def invoice_view(request,id):
	invoice_obj = Invoice.objects.get(id=id)
	context = {
		'invoice_obj':invoice_obj
	}
	return render(request, "invoice/invoice_view.html", context)

class InvoiceList(LoginRequiredMixin, ListView):
	model = Invoice
	template_name = 'invoice/invoice_list.html'
	context_object_name = 'invoice_list'
	ordering = "-pk"

	def get_context_data(self,**kwargs):
		data = super(InvoiceList,self).get_context_data(**kwargs)
		data["invoice_form"] = InvoiceForm()
		data["invoice_ini_form"] = invoice_inline_form()
		return data

@login_required
def create_invoice(request):
	if request.method == 'POST':
		form1 = InvoiceForm(request.POST)
		form2 = invoice_inline_form(request.POST)
		if form1.is_valid() and form2.is_valid():
			form1.instance.created_by = request.user
			inv_form = form1.save()
			with transaction.atomic():
				form2.instance = inv_form
				form2.save()

			inv_total = 0
			inv_obj = Invoice.objects.get(id=form1.instance.id)
			inv_pro = InvoiceProduct.objects.filter(invoice=inv_obj)

			for product in inv_pro:
				pro_total = product.quantity * product.price
				product.total_price = pro_total
				product.save()
				inv_total = inv_total + pro_total


				inven_obj = Inventory.objects.get(product=product.product)
				inven_obj.stock = inven_obj.stock - product.quantity
				inven_obj.save()

			discount_price = inv_total * inv_obj.discount / 100
			inv_final_price = inv_total - discount_price

			inv_obj.total_invoice_price = inv_final_price
			inv_obj.save()




		return redirect("/invoice/list/")

@login_required
def update_invoice(request,id):
	in_obj = Invoice.objects.get(id=id)
	if request.method == 'POST':
		form1 = InvoiceForm(request.POST, instance=in_obj)
		form2 = invoice_inline_form(request.POST, instance=in_obj)
		if form1.is_valid() and form2.is_valid():
			form1.instance.created_by = request.user
			inv_form = form1.save()
			with transaction.atomic():
				form2.instance = inv_form
				form2.save()

			inv_total = 0
			inv_obj = Invoice.objects.get(id=form1.instance.id)
			inv_pro = InvoiceProduct.objects.filter(invoice=inv_obj)

			for product in inv_pro:
				pro_total = product.quantity * product.price
				product.total_price = pro_total
				product.save()
				inv_total = inv_total + pro_total


			discount_price = inv_total * inv_obj.discount / 100
			inv_final_price = inv_total - discount_price

			inv_obj.total_invoice_price = inv_final_price
			inv_obj.save()


			pros = Product.objects.all()
			for pro in pros:
				inv_pros = InvoiceProduct.objects.filter(product=pro)
				inventory = Inventory.objects.get(product=pro)
				total_stock = inventory.total_stock
				total = 0
				for inv_pr in inv_pros:
					total = total + inv_pr.quantity

				inventory.stock = total_stock - total
				inventory.save()
				total = 0


			return redirect("/invoice/list/")

	else:
		form1 = InvoiceForm(instance=in_obj)
		form2 = invoice_inline_form(instance=in_obj)

		context = {
			'form1':form1,
			'form2':form2,
		}

	return render(request, 'invoice/invoice_update.html', context)

src/templates/invoice/invoice_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block js %}
<script>
$(document).ready(function() {
  $('.invoice_product_div').formset({
    addText: 'Add More Product',
    deleteText: 'DELETE',
    prefix: 'invoiceproduct_set',
  });
});
</script>
{% endblock %}


{% block contain %}

<div class="container">
  <div class="inner-container">
  <button id="myBtn">Create Invoice</button>
    <div id="myModal" class="modal">
      <div class="modal-content" style="width: 60%;">
        <div class="modal-header">
          <span class="close">&times;</span>
          <h2>Create Invoice</h2>
        </div>
        <div class="modal-body" style="margin-bottom: 10%;">
          <form action="{% url 'invoice_create' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div style="width:70%; float:left;margin-bottom:20px;">
              <p style="font-size: 20px;font-weight: bold;color: #347ab4;">
                RespoCare
               </p>
               <small style="font-size: 13px;font-weight: normal;">(Specialist Respiratory Care)</small><br>
                <small style="font-size: 13px;font-weight: normal;color: #347ab4;">
                  155 (1st Floor),
                  Aziz Medicine & Medical Equipment Market<br>
                  Shahbag, Dhaka-1000.<br>
                  Mobile: 01712-166060, 01943-795007 <br>
                  E-mail: carerespo@gmail.com
                </small>
            </div>
            <div style="width:30%; float:left;margin-bottom:20px;">
              <img src="{% static 'images/logo.png' %}" style="width: 65%;">
            </div>

            <p style="text-align: center;padding: 7%;font-weight: bold;">INVOICE</p>
              {% render_field invoice_form.invoice_to rows="3" placeholder="INVOICE TO (CLIENT INFO)"  %}

            <small style="float: right;margin-right: 9%;">
              Invoice Date: <input type="date" name="invoice_date" id="id_invoice_date" value="{% now 'Y-m-d' %}">
            </small>
            <small style="float: right;margin-right: -4.5%;margin-top: -24px;">
              Discount percentage: {% render_field invoice_form.discount style="width: 28%;"  %}
            </small>

                <table id="table" style="margin-top: 3%;">
                    <tr>
                        <th class="col col-2">Product</th>
                        <th class="col col-3">Quantity</th>
                        <th class="col col-4">Price</th>
                        <th class="col col-5">Delete</th>
                    </tr>

                    {{ invoice_ini_form.management_form }}

                    {% for form in invoice_ini_form.forms %}
                      {% for hidden in form.hidden_fields %}
                          {{ hidden }}
                      {% endfor %}


                   <tr class="invoice_product_div">
                    <td>{% render_field form.product %}</td>
                    <td>{% render_field form.quantity %}</td>
                    <td>{% render_field form.price %}</td>
                    <td>{{ form.DELETE }}</td>
                  </tr>

                  {% endfor %}


                </table>
                 <div style="width:100%">
                   {% render_field invoice_form.invoice_note rows="3" style="margin-top: 1%;" placeholder="INVOICE NOTES" %}
                 </div>
                <button type="submit" style="margin-top: 12px">Create Invoice</button>
                <br>
                <br>
                <br>
            </div>
          </form>
        </div>
      </div>




<div class="invoicelist">
    <div class="table-header">
        <h3>Invoice List</h3>
        <hr>
    </div>
    <div class="table-list">
        <table id="table">
            <tr>
                <th class="col col-1">#Id</th>
                <th class="col col-2">Invoice To</th>
                <th class="col col-5">Invoice Date</th>
                <th class="col col-5">Created By</th>
                <th class="col col-5">Invoice Total</th>
                <th class="col col-6">ACTION</th>
            </tr>
            {% for invoice in invoice_list %}
           <tr>
             <td>{{ invoice.id }}</td>
             <td>{{ invoice.invoice_to }}</td>
             <td>{{ invoice.invoice_date|date:"Y-m-d" }}</td>
             <td>{{ invoice.created_by }}</td>
             <td>{{ invoice.total_invoice_price }} /-</td>
             <td>
               <a href="{% url 'update_invoice' invoice.id %}"><i class="far fa-file-alt"></i></a>
               <a href="{% url 'invoice_view' invoice.id %}"><i class="far fa-eye"></i></a>
               <a href="{% url 'pdf_view' invoice.id %}" target="_blank"><i class="fas fa-file-pdf"></i></a>
             </td>
          </tr>
          {% endfor %}
      </table>
    </div>
</div>
    </div>
</div>

<style media="screen">
  .add-row{
    position: absolute;
    margin-left: 79%;
    margin-top: 6px;
    background-color: cadetblue;
    padding: 6px;
    font-size: 15px;
    color: #fff;
  }
</style>

{% endblock %}

src/templates/invoice/invoice_pdf_view.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Invoice</title>
    <link href="{% static 'css/pdf/pdf.css' %}" rel="stylesheet">
    <link href="{% static 'css/pdf/pdf-narrow.css' %}" rel="stylesheet">
    <style>
      .invo_heading{
        font-size: 20px;
        font-weight: bold;

      }

      .invo_color{
        color: #347ab4 !important;
      }
      .inv_table{
        background-color: #edededcc !important;
        color: #7f7f7f !important;
      }

      thead { display: table-header-group }
      tfoot { display: table-row-group }
      tr { page-break-inside: avoid }

    </style>
  </head>

  <body>

    <div class="container">
      <div class="row marketing">

<div class="row">
        <div class="col-xs-6">
          <div class="col-xs-12">
          <div class="com_container" style="line-height: 16px;">
            <p class="invo_color" style="font-size: 20px;font-weight: bold;margin-bottom:0px">
              RespoCare
             </p>
             <small style="font-size: 13px;font-weight: normal;">(Specialist Respiratory Care)</small><br>
              <small class="invo_color" style="font-size: 13px;font-weight: normal;">
                155 (1st Floor),
                Aziz Medicine & Medical Equipment Market,
                Shahbag, Dhaka-1000.<br>
                Mobile: 01712-166060, 01943-795007 <br>
                E-mail: carerespo@gmail.com
              </small>
          </div>
          </div>
        </div>

        <div class="col-xs-6">
          <img src="{% static 'images/logo.png' %}" style="width: 50%;float: right;">
        </div>

        <div class="col-xs-12">
          <center class="invo_heading" style="margin-top: 4%;">INVOICE</center>
          <br>
          <br>
          <br>
        </div>
</div>

<div class="row">
        <div class="col-xs-6">
          <div class="col-xs-12">
            <small style="text-decoration: underline;">CLIENT INFO: </small>
          </div>
          <div class="col-xs-12" style="font-size: 13px;">
            {{ invoice_obj.invoice_to|linebreaks }}
          </div>
        </div>

        <div class="col-xs-6">
            <div class="col-xs-4">
              <small>INVOICE ID</small>
            </div>
            <div class="col-xs-8" style="border-left: 1px solid #7f7f7f;">
              #{{ invoice_obj.id }}
            </div>


            <div class="col-xs-4">
              <small>DATE</small>
            </div>
            <div class="col-xs-8" style="border-left: 1px solid #7f7f7f;">
              {{ invoice_obj.invoice_date|date:"Y-m-d" }}
            </div>
        </div>

</div>



<div class="col-xs-12" style="margin-top: 50px">
  <table class="table table-bordered">
    <thead>
      <tr class="inv_table">
        <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Line Total</th>
      </tr>
    </thead>
    <tbody>




{% for pro in invoice_obj.invoiceproduct_set.all %}
   <tr class="invoice_product_div">
    <td>{{ pro.product.name }}</td>
    <td>{{ pro.price }}</td>
    <td>{{ pro.quantity }}</td>
    <td>{{ pro.total_price }}</td>
  </tr>
{% endfor %}
<tr class="invoice_product_div">
 <td></td>
 <td></td>
 <td>Discount</td>
 <td>{{ invoice_obj.discount }} %</td>
</tr>
<tr class="invoice_product_div">
<td></td>
<td></td>
<td>Total</td>
<td>{{ invoice_obj.total_invoice_price }} TK</td>
</tr>



    </tbody>
  </table>
</div>


    <div class="row">
      <div class="col-xs-12">
        <div class="col-xs-12">
          Note: <br>
          {{ invoice_obj.invoice_note|linebreaks }}
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <div class="col-xs-12">
          <div class="pull-right">
            <small>-----------------------------</small><br>
            <small>(company signature)</small>
          </div>
        </div>
      </div>
    </div>

      </div>


    </div>

  </body>
</html>

src/templates/invoice/invoice_update.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block js %}
<script>
$(document).ready(function() {
  $('.invoice_product_update_div').formset({
    addText: 'Add More Product',
    deleteText: 'DELETE',
    prefix: 'invoiceproduct_set',
  });
});
</script>
{% endblock %}


{% block contain %}
<div style="margin-top: 1%;margin-left: 17%;">
	<p>Update Invoice</p>
	<hr>
</div>

<div style="margin-left: 17%;margin-top: 2%;margin-right: 2%;">
  <form action="{% url 'update_invoice' form1.instance.id %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
    <div style="width:70%; float:left;margin-bottom:20px;">
      <p style="font-size: 20px;font-weight: bold;color: #347ab4;">
        RespoCare
       </p>
       <small style="font-size: 13px;font-weight: normal;">(Specialist Respiratory Care)</small><br>
        <small style="font-size: 13px;font-weight: normal;color: #347ab4;">
          155 (1st Floor),
          Aziz Medicine & Medical Equipment Market<br>
          Shahbag, Dhaka-1000.<br>
          Mobile: 01712-166060, 01943-795007 <br>
          E-mail: carerespo@gmail.com
        </small>
    </div>
    <div style="width:30%; float:left;margin-bottom:20px;">
      <img src="{% static 'images/logo.png' %}" style="width: 68%;">
    </div>

    <p style="text-align: center;padding: 7%;font-weight: bold;width:68%">INVOICE</p>
      {% render_field form1.invoice_to rows="3" placeholder="INVOICE TO (CLIENT INFO)"  %}

    <small style="float: right;margin-right: 9%;">
      Invoice Date: <input type="date" name="invoice_date" id="id_invoice_date" value="{% now 'Y-m-d' %}">
    </small>
    <small style="float: right;margin-right: -29.5%;margin-top: 32px;">
      Discount percentage: {% render_field form1.discount style="width: 28%;"  %}
    </small>

        <table id="table" style="margin-top: 3%;">
            <tr>
                <th class="col col-2">Product</th>
                <th class="col col-3">Quantity</th>
                <th class="col col-4">Price</th>
                <th class="col col-5">Delete</th>
            </tr>
            {{ form2.management_form }}

            {% for form in form2.forms %}
              {% for hidden in form.hidden_fields %}
                  {{ hidden }}
              {% endfor %}

           <tr class="invoice_product_update_div">
            <td>{% render_field form.product %}</td>
            <td>{% render_field form.quantity %}</td>
            <td>{% render_field form.price %}</td>
            <td>{{ form.DELETE }}</td>
          </tr>

          {% endfor %}


        </table>
         <div style="width:100%">
           {% render_field form1.invoice_note rows="3" style="margin-top: 1%;" placeholder="INVOICE NOTES" %}
         </div>
        <button type="submit" style="margin-top: 12px;margin-bottom: 7%;">Update Invoice</button>
  </form>
</div>
<style media="screen">
  .add-row{
    position: absolute;
    margin-left: 71%;
    margin-top: 6px;
    background-color: cadetblue;
    padding: 6px;
    font-size: 15px;
    color: #fff;
  }

#id_invoice_to{
  padding: 10px;
}

#id_invoice_note{
  padding: 10px;
}

</style>
{% endblock %}

src/templates/invoice/invoice_view.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block contain %}
<div style="margin-top: 1%;margin-left: 17%;">
	<p>INVOICE VIEW</p>
	<hr>
</div>
<div class="container">
  <div class="inner-container">

            <div style="width:70%; float:left;margin-bottom:20px;">
              <p style="font-size: 20px;font-weight: bold;color: #347ab4;">
                RespoCare
               </p>
               <small style="font-size: 13px;font-weight: normal;">(Specialist Respiratory Care)</small><br>
                <small style="font-size: 13px;font-weight: normal;color: #347ab4;">
                  155 (1st Floor),
                  Aziz Medicine & Medical Equipment Market<br>
                  Shahbag, Dhaka-1000.<br>
                  Mobile: 01712-166060, 01943-795007 <br>
                  E-mail: carerespo@gmail.com
                </small>
            </div>
            <div style="width:30%; float:left;margin-bottom:20px;">
              <img src="{% static 'images/logo.png' %}" style="width: 68%;">
            </div>

            <p style="text-align: center;padding: 7%;font-weight: bold;width: 68%;">INVOICE</p>
            <p style="margin-bottom: 8px">CLIENT INFO</p>
            <span style="font-size: 15px;">{{ invoice_obj.invoice_to|linebreaks }}</span>

            <small style="float: right;margin-right: 9%;font-size: 15px;">
              Invoice Date: {{ invoice_obj.invoice_date|date:"Y-m-d" }}
            </small>
            <small style="float: right;margin-right: -16.5%;margin-top: -23px;font-size: 15px;">
              Discount Amount: {{ invoice_obj.discount }} Taka
            </small>

                <table id="table" style="margin-top: 3%;">
                    <tr>
                        <th class="col col-2">Product</th>
                        <th class="col col-3">Price</th>
                        <th class="col col-4">Quantity</th>
                        <th class="col col-5">Line Total</th>
                    </tr>
                    {% for pro in invoice_obj.invoiceproduct_set.all %}
                       <tr class="invoice_product_div">
                        <td>{{ pro.product.name }}</td>
                        <td>{{ pro.price }}</td>
                        <td>{{ pro.quantity }}</td>
                        <td>{{ pro.total_price }}</td>
                      </tr>
                    {% endfor %}
                    <tr class="invoice_product_div">
                     <td></td>
                     <td></td>
                     <td>Discount</td>
                     <td>{{ invoice_obj.discount }} %</td>
                   </tr>
                   <tr class="invoice_product_div">
                    <td></td>
                    <td></td>
                    <td>Total</td>
                    <td>{{ invoice_obj.total_invoice_price }}</td>
                  </tr>
                </table>
                 <div style="width:100%">
                   <br>
                   <small>Note</small>
                   <span style="margin-top: 5px;font-size: 13px;">{{ invoice_obj.invoice_note|linebreaks }}</span>

                 </div>

        </div>
      </div>


{% endblock %}